---
- name: Load OS specific vars
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Disable handler for Docker testing
  ansible.builtin.set_fact:
    handler_enabled: true
  tags: molecule-notest

  # this is only really needed for Molecule images
- name: Ensure systemd installed
  ansible.builtin.package:
    name: systemd

- name: Ensure wireguard installed
  ansible.builtin.package:
    name: "{{ vpn_package }}"

- name: Wireguard netdev configuration
  ansible.builtin.template:
    src: templates/wg1.netdev.j2
    dest: "/etc/systemd/network/{{ vpn_interface }}.netdev"
    owner: root
    group: systemd-network
    mode: 0640
  notify: restart systemd-networkd

- name: Wireguard network configuration
  ansible.builtin.template:
    src: templates/wg1.network.j2
    dest: "/etc/systemd/network/{{ vpn_interface }}.network"
    owner: root
    group: systemd-network
    mode: 0644
  notify: restart systemd-networkd

- name: Wireguard enable NDP proxy
  ansible.builtin.lineinfile:
    dest: "{{ vpn_ndp_config }}"
    insertafter: '^\[Network\]'
    line: IPv6ProxyNDP=yes
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-networkd
  when: vpn_ndp_config is defined

- name: Wireguard NDP proxy configuration
  ansible.builtin.lineinfile:
    dest: "{{ vpn_ndp_config }}"
    insertafter: '^\[Network\]'
    line: "IPv6ProxyNDPAddress={{ item.address6 }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ vpn_clients }}"
  notify: restart systemd-networkd
  when: vpn_ndp_config is defined

- name: Systemd-networkd service enabled
  ansible.builtin.service:
    name: systemd-networkd
    state: started
    enabled: true
  tags: molecule-notest

- name: Wireguard client file directory
  ansible.builtin.file:
    dest: "{{ vpn_clients_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Wireguard client configuration file
  ansible.builtin.template:
    dest: "{{ vpn_clients_dir }}/{{ item.name }}.conf"
    src: templates/client.j2
    owner: root
    group: root
    mode: 0600
  loop: "{{ vpn_clients }}"
