---
name: release

on:
  push:
    tags: ['*']

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Package
        uses: a7ul/tar-action@v1.1.2
        with:
          files: .
          command: c
          outPath: release.tar.gz
          
      - name: Build and Deploy Collection
        uses: 0x022b/galaxy-role-import-action@1.0.0
        with:
          galaxy_api_key: '${{ secrets.ANSIBLE_GALAXY_TOKEN }}'
          
      - name: debug
        run: ls -lR
        
      - name: Sign release with Sigstore
        uses: sigstore/gh-action-sigstore-python@v0.0.9
        with:
          inputs: release.tar.gz
          release-signing-artifacts: true

        
    

 
        
        
          
