---
name: release

on:
  push:
    tags: ['*']

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Ansible Galaxy Publish
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: '${{ secrets.ANSIBLE_GALAXY_TOKEN }}'
          
      - name: debug
        run: ls -lR
        
      - name: Sign release with Sigstore
        uses: sigstore/gh-action-sigstore-python@v0.0.9
        with:
          inputs: *.tar.gz *.zip
          release-signing-artifacts: true

        
    

 
        
        
          
