---
name: release

on:
  push:
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Sign release with Sigstore
        uses: sigstore/gh-action-sigstore-python@v0.0.9
        with:
          release-signing-artifacts: true
          upload-signing-artifacts: true

      - name: Build and Deploy Collection
        uses: 0x022b/galaxy-role-import-action@1.0.0
        with:
          galaxy_api_key: '${{ secrets.ANSIBLE_GALAXY_TOKEN }}'
          identity-token: '${{ secrets.SIGSTORE_TOKEN }}'
